window.BOARD = {
  updated: "2026-10-09",
  timezone: "Africa/Lagos",
  profile: "Nigerian Mechanical Engineering undergraduate, 300 level, aerospace / space focus",
  summary: "EPFL E3 opens 12 Oct (closes 1 Nov). AIAA DBF proposals 15-31 Oct. Local: Carewave Aspire (9 Nov) and Shell SIWES are open. KAUST and IAESTE remain the funded abroad routes.",
  stats: { urgent: 2, open: 4, forecast: 14, excluded: 18 },
  deadlines: [
    { date: "2026-10-12", label: "EPFL E3 opens", hint: "Submit in week one", status: "urgent" },
    { date: "2026-10-15", label: "AIAA DBF opens", hint: "Proposal window; fly-off unfunded", status: "urgent" },
    { date: "2026-10-16", label: "KAUST VSRP file", hint: "Rolling; passport + faculty email", status: "open" },
    { date: "2026-10-23", label: "SG Nigeria ticket", hint: "Abuja pass only; no travel pay", status: "excluded" },
    { date: "2026-10-31", label: "AIAA DBF close", hint: "Before 17:00 ET", status: "urgent" },
    { date: "2026-11-01", label: "EPFL E3 deadline", hint: "Summer 2027 research", status: "urgent" },
    { date: "2026-11-01", label: "Caltech SURF opens", hint: "Campus track only for internationals", status: "forecast" },
    { date: "2026-11-08", label: "IEEE WIE close", hint: "Excluded unless 2 years WIE", status: "excluded" },
    { date: "2026-11-09", label: "Carewave Aspire close", hint: "Local N500k; Mech eligible", status: "open" },
    { date: "2026-11-15", label: "Amelia Earhart", hint: "Doctoral women only", status: "excluded" },
    { date: "2026-11-16", label: "NASA ORBIT close", hint: "US enrolment only", status: "excluded" },
    { date: "2026-11-22", label: "ESA Experiments", hint: "Eligible states only; skip", status: "excluded" },
    { date: "2026-12-01", label: "TU Delft van Effen", hint: "MSc only; after degree", status: "forecast" },
    { date: "2027-01-30", label: "IAF ESL forecast", hint: "IAC 2027 Poznan grant", status: "forecast" },
    { date: "2027-01-31", label: "CERN Summer forecast", hint: "Need 6 semesters by summer", status: "forecast" },
    { date: "2027-03-01", label: "Caltech SURF close", hint: "Confirm on SFP site", status: "forecast" },
    { date: "2027-05-15", label: "AfSA workshop watch", hint: "2026 call closed 15 May", status: "forecast" },
    { date: "2027-05-30", label: "PTDF ISS forecast", hint: "2026 closed June; undergrad often 200L", status: "forecast" },
    { date: "2027-09-01", label: "GEF bridge window", hint: "2026 closed 30 Sep", status: "forecast" }
  ],
  opportunities: [
    {
      id: "epfl-e3",
      name: "EPFL Excellence in Engineering (E3)",
      status: "urgent",
      type: "Summer research",
      destination: "EPFL, Switzerland",
      level: "BSc / MSc (2+ years completed)",
      covers: "Paid research stay (about CHF 1,800/mo in recent cycles). Confirm 2027 stipend on portal. Travel reimbursement on request. 8-12 weeks from May.",
      eligibility: "International students. Mechanical engineering is named on the official page. Strong academic record expected.",
      deadline: "Portal opens 12 Oct 2026 and closes 1 Nov 2026",
      link: "https://eee.epfl.ch/",
      linkLabel: "Open EPFL E3 site",
      aerospace: "Mechanical, microengineering, and materials research next to aerospace structures, UAVs, and mechanisms.",
      next: "CV, English transcript, statement tied to a lab, two referees ready before 12 October. Submit in week one."
    },
    {
      id: "aiaa-dbf",
      name: "AIAA Design/Build/Fly 2027",
      status: "urgent",
      type: "Team aircraft competition",
      destination: "Online proposal; fly-off Tucson, Arizona",
      level: "Undergraduate student teams",
      covers: "Competition slot and recognition. Does not pay travel, shipping, or AIAA membership.",
      eligibility: "Teams worldwide. AIAA student membership required. Nigeria is not on the sanctions list that blocks prize money.",
      deadline: "Proposals open 15 Oct 2026 08:00 ET and close 31 Oct 2026 before 17:00 ET",
      link: "https://aiaa.org/get-involved/university-students/dbf/",
      linkLabel: "AIAA DBF page",
      aerospace: "Direct aircraft design, structures, propulsion, and flight test.",
      next: "Enter only if a campus team can file a proposal in two weeks. Do not pay an agent."
    },
    {
      id: "kaust-vsrp",
      name: "KAUST Visiting Student Research Program (VSRP)",
      status: "open",
      type: "Research internship",
      destination: "KAUST, Saudi Arabia",
      level: "3rd-year bachelor's or master's",
      covers: "USD 1,000/month, private room, visa and airfare, health insurance, 2-6 months.",
      eligibility: "All nationalities. GPA about 3.5/4.0. English. Transcript, recommendation, valid passport. One application at a time.",
      deadline: "Rolling (arrival at least 6 weeks after submission)",
      link: "https://admissions.kaust.edu.sa/study/internships",
      linkLabel: "Open KAUST internships",
      aerospace: "Fluids, combustion, composites, thermal systems - mechanical core of propulsion and airframes.",
      next: "Pick a Mechanical / PSE faculty project, email a short research note, then submit."
    },
    {
      id: "iaeste",
      name: "IAESTE Nigeria paid internships",
      status: "open",
      type: "Paid internship / exchange",
      destination: "80+ countries (offer-dependent)",
      level: "Enrolled undergrad, age 19-30, usually after 4 semesters",
      covers: "Local living-cost salary; visa and accommodation support. You pay national participation fee plus passport.",
      eligibility: "Nigerian university students via IAESTE Nigeria. Mechanical engineering is a core field.",
      deadline: "Offer-driven (peak after January exchange conference)",
      link: "https://iaeste.ng/index.php/students/",
      linkLabel: "IAESTE Nigeria students",
      aerospace: "Filter offers for aerospace, automotive, energy, manufacturing, or design offices.",
      next: "Email nigeria@iaeste.org with English CV, subject list, and passport biodata. Pay only the national committee."
    },
    {
      id: "carewave",
      name: "Carewave Aspire Scholarship (CASP) 2026",
      status: "open",
      type: "Local undergraduate scholarship",
      destination: "Nigeria (cash award)",
      level: "Nigerian undergrads in federal universities (age 18-25 typical)",
      covers: "About N500,000 per year if selected. Local cash only - useful as passport, visa, or IAESTE fee bridge.",
      eligibility: "Nigerian citizen. Mechanical Engineering is listed under STEM. Some listings require CGPA about 4.5/5.0 and proof of financial need. Confirm on the portal.",
      deadline: "9 November 2026",
      link: "https://portal.carewavefoundation.org/scholarships/apply?scholarshipId=SCH-2026-946543",
      linkLabel: "Carewave apply portal",
      aerospace: "Not a space placement. Local cash that can fund travel documents for abroad routes.",
      next: "Create a portal account, upload admission and need documents, and submit before 9 November. Never pay an agent."
    },
    {
      id: "shell-siwes",
      name: "Shell Nigeria SIWES / Student Industrial Training",
      status: "open",
      type: "Local paid industrial training",
      destination: "Shell Companies in Nigeria",
      level: "Full-time Nigerian university or polytechnic undergrad",
      covers: "Work attachment with professionals. Stipend is not published on the careers page - confirm if selected.",
      eligibility: "Nigerian citizen. Engineering is listed. University CGPA minimum 3.5/5.0. School SIWES authorisation required.",
      deadline: "Open application form (rolling; only successful applicants contacted)",
      link: "https://www.shell.com.ng/careers/students-and-graduates/student-industrial-training-and-internship-program.html",
      linkLabel: "Shell SIWES page",
      aerospace: "Energy systems, materials, and industrial discipline - mechanical bridge, not aircraft design.",
      next: "Complete the official Microsoft Forms link from the Shell page with SIWES letter ready. No application fee."
    },
    {
      id: "sipga",
      name: "A*STAR SIPGA (Singapore)",
      status: "forecast",
      type: "Research attachment",
      destination: "A*STAR institutes, Singapore",
      level: "3rd / 4th year undergrad or master's",
      covers: "About SGD 2,000/month for 2-6 months in past cycles. Travel not always fully covered.",
      eligibility: "International STEM; on track for at least Second Class Upper equivalent.",
      deadline: "Historical cycles ~31 Mar / 31 Jul / 31 Oct - programme URL was 404 on 3 Oct 2026",
      link: "https://www.a-star.edu.sg/sris/training-and-mentorship",
      linkLabel: "A*STAR training page",
      aerospace: "Materials, robotics, manufacturing, computational engineering bridge - not a launch internship.",
      next: "Open the project list. Apply only if a mechanical-relevant project is posted."
    },
    {
      id: "cern-summer",
      name: "CERN Summer Student Programme",
      status: "forecast",
      type: "Summer technical studentship",
      destination: "CERN, Geneva, Switzerland",
      level: "Bachelor's or master's; at least 6 semesters by summer start",
      covers: "94 CHF/day, insurance, housing help, possible travel support; 8-13 weeks.",
      eligibility: "All nationalities (US/Canada/Japan use national routes). Engineering eligible. Still enrolled. No open summer posts on 9 Oct 2026.",
      deadline: "Forecast close end of January 2027 - confirm on careers.cern",
      link: "https://careers.cern/programmes/summer-studentship/",
      linkLabel: "CERN Summer Studentship",
      aerospace: "Vacuum, cryogenics, detectors, mechanical systems at a major lab.",
      next: "Target summer 2027 only if six semesters will be complete; otherwise plan 2028."
    },
    {
      id: "iaf-esl",
      name: "IAF Emerging Space Leaders Grant",
      status: "forecast",
      type: "Conference travel grant",
      destination: "IAC 2027, Poznan, Poland",
      level: "Students and young professionals, age 21-35",
      covers: "Support to attend the International Astronautical Congress and present a paper or join a selected panel.",
      eligibility: "Worldwide. Students at a recognised university qualify. 2026 call closed 30 January 2026.",
      deadline: "Forecast late January 2027 - confirm on the grant platform",
      link: "https://www.iaf-grant-programme.org/",
      linkLabel: "IAF ESL platform",
      aerospace: "Direct space-sector congress: technical papers, agency and industry sessions.",
      next: "Draft a mechanical or aerospace abstract so a January call is usable."
    },
    {
      id: "sgac",
      name: "SGAC / Space Generation Congress scholarships",
      status: "forecast",
      type: "Conference scholarship",
      destination: "SGC and IAC 2027, Poznan, Poland",
      level: "Students and young professionals 18-35",
      covers: "Often partial travel or registration for SGC and related events.",
      eligibility: "Open worldwide. Competitive; essay and CV driven. 2026 SGLA closed in June. Logo scholarship closed 18 Sep 2026.",
      deadline: "Typical spring call before autumn congress",
      link: "https://spacegeneration.org/scholarships",
      linkLabel: "SGAC scholarships",
      aerospace: "Direct space-sector networking and policy/technical sessions.",
      next: "Watch the scholarships page from March; prepare a one-page space motivation statement."
    },
    {
      id: "afsa-st",
      name: "AfSA / ESA Spacecraft Testing Workshop",
      status: "forecast",
      type: "Hands-on workshop",
      destination: "ESEC-Galaxia, Belgium",
      level: "African BSc, MSc, or PhD in engineering or science, age 18-35",
      covers: "2026 workshop was a funded training week led by ESA engineers. Next-cycle funding not yet published.",
      eligibility: "African nationals. 2026 deadline was 15 May 2026 and has passed.",
      deadline: "Next cycle not announced - watch mid-spring 2027",
      link: "https://africanspaceagency.org/call-for-applications-spacecraft-testing-workshop/",
      linkLabel: "AfSA workshop page",
      aerospace: "Direct spacecraft testing with ESA engineers.",
      next: "Keep a one-page CV and transcript ready for a spring 2027 call."
    },
    {
      id: "afsa-eossd",
      name: "AfSA / ESA Earth Observation Satellite System Design",
      status: "forecast",
      type: "Training course",
      destination: "ESEC-Galaxia, Belgium, plus online week",
      level: "African BSc, MSc, or PhD in engineering or science, age 18-35",
      covers: "2026 course was a funded training week. Next-cycle funding not yet published.",
      eligibility: "African nationals with maths and physics. 2026 deadline was 19 June 2026 and has passed.",
      deadline: "Next cycle not announced - watch spring 2027",
      link: "https://africanspaceagency.org/call-for-applications-earth-observation-satellite-system-design-training-course-2026/",
      linkLabel: "AfSA EOSSD page",
      aerospace: "Satellite system design with ESA Academy trainers.",
      next: "Keep endorsement letter and transcript ready for a spring 2027 call."
    },
    {
      id: "unisec",
      name: "UNISEC Mission Idea Contest / CLTP",
      status: "forecast",
      type: "Competition / training",
      destination: "Japan / rotating hosts",
      level: "University student teams and individuals",
      covers: "Sometimes partial travel for selected participants.",
      eligibility: "International student teams. PreMIC10 abstract deadline 22 July 2026 has passed. CLTP15 deadline 22 April 2026 has passed.",
      deadline: "Next CLTP / MIC window forecast 2027",
      link: "https://www.unisec-global.org/calendar.html",
      linkLabel: "UNISEC calendar",
      aerospace: "CubeSat / CanSat hands-on pathway into small-satellite engineering.",
      next: "Join or form a campus satellite team early; monitor the calendar."
    },
    {
      id: "airbus-fyi",
      name: "Airbus Fly Your Ideas",
      status: "forecast",
      type: "Student team competition",
      destination: "Online, then an airshow final",
      level: "Bachelor's, master's, or PhD teams of 3-5",
      covers: "Mentoring and finalist visibility. Not a paid internship.",
      eligibility: "Any university worldwide if enrolled for the contest. 2026 round is closed.",
      deadline: "2026 Round 1 closed 24 March 2026. Next edition not announced - forecast early 2027.",
      link: "https://www.airbus.com/en/flyyourideas",
      linkLabel: "Airbus Fly Your Ideas",
      aerospace: "Direct Airbus challenge on aerospace systems.",
      next: "Build a 3-5 person team. Do not pay an agent to register a closed round."
    },
    {
      id: "caltech-surf",
      name: "Caltech SURF campus track",
      status: "forecast",
      type: "Summer research fellowship",
      destination: "Caltech campus, Pasadena, USA (not JPL)",
      level: "Continuing undergraduates, including visiting internationals",
      covers: "Stipend about USD 8,000 for 10 weeks in recent cycles. Housing and international airfare are not fully covered.",
      eligibility: "Campus track open to international undergraduates with a faculty mentor. JPL track is US citizens and permanent residents only.",
      deadline: "Reported open 1 Nov 2026, due about 1 Mar 2027 - confirm on the SFP site",
      link: "https://sfp.caltech.edu/programs/surf",
      linkLabel: "Caltech SURF",
      aerospace: "GALCIT and fluids/structures labs are the aerospace bridge. JPL is blocked.",
      next: "Identify a campus mentor in November. Do not apply to the JPL track."
    },
    {
      id: "tudelft-effen",
      name: "TU Delft Justus and Louise van Effen Scholarship",
      status: "forecast",
      type: "Postgraduate scholarship",
      destination: "TU Delft, Netherlands",
      level: "Requires completed bachelor's for a 2-year MSc",
      covers: "Full first-year tuition for a regular MSc, including Aerospace Engineering. Confirm living allowance on the official page.",
      eligibility: "International applicants with a completed relevant degree. Not open to a current 300-level student this cycle.",
      deadline: "1 Dec 2026, 23:59 CET for 2027-2029 MSc applicants",
      link: "https://www.tudelft.nl/onderwijs/studievoorlichting/praktische-zaken/scholarships",
      linkLabel: "TU Delft scholarships",
      aerospace: "Direct route into the TU Delft Aerospace Engineering MSc after graduation.",
      next: "File under post-graduation targets. Do not apply before the degree is complete."
    },
    {
      id: "commonwealth",
      name: "Commonwealth Master's Scholarship (UK)",
      status: "forecast",
      type: "Postgraduate scholarship",
      destination: "United Kingdom",
      level: "Requires completed bachelor's degree",
      covers: "Fully funded one-year master's (typical CSC package).",
      eligibility: "Not for current undergrads without a degree. Engineering and technology is a theme.",
      deadline: "CSC close 20 Oct 2026 at 16:00 UK time - do not apply this cycle",
      link: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
      linkLabel: "CSC Master's scholarships",
      aerospace: "Post-graduation route into UK aerospace / mechanical master's programmes.",
      next: "File under 2028/29 targets after graduation."
    },
    {
      id: "ptdf-iss",
      name: "PTDF In-Country Scholarship Scheme (ISS)",
      status: "forecast",
      type: "Local undergraduate / postgraduate scholarship",
      destination: "Nigerian public universities",
      level: "Undergrad often requires current 200 level; MSc and PhD have separate tracks",
      covers: "Tuition support and stipends for oil-and-gas related fields in public universities. Mechanical Engineering is listed.",
      eligibility: "Nigerian citizens in public universities. 2026/27 undergrad window closed 5 June 2026. Confirm level rules on the next advert.",
      deadline: "Forecast April-June 2027 for the next ISS cycle - confirm on scholarship.ptdf.gov.ng",
      link: "https://scholarship.ptdf.gov.ng/guidelines",
      linkLabel: "PTDF guidelines",
      aerospace: "Energy and mechanical capacity building - not a direct space agency placement.",
      next: "As a 300-level student, verify whether undergrad ISS is limited to 200 level. Watch the portal for OSS overseas calls separately."
    },
    {
      id: "gef-bridge",
      name: "Gabriel Ezenri Foundation (bridge funding)",
      status: "forecast",
      type: "Domestic bridge scholarship",
      destination: "Nigeria (fee cash only)",
      level: "Nigerian undergraduates",
      covers: "Up to N500,000 for the session if awarded. Use only for passport, visa, or IAESTE fees.",
      eligibility: "Nigerian students at accredited institutions. Continuing students need CGPA 3.5/5. No application fee.",
      deadline: "2026 window closed 30 Sep 2026. Forecast 1-30 Sep 2027",
      link: "https://gabrielezenrifoundation.org/apply",
      linkLabel: "GEF apply page",
      aerospace: "Not aerospace. Bridge cash only.",
      next: "Do not chase the closed 2026 form. Never pay an agent."
    },
    {
      id: "cars4mars",
      name: "Cars4Mars African Rover Challenge",
      status: "forecast",
      type: "Rover competition",
      destination: "Africa (2026 final at SANSA, South Africa)",
      level: "University and college students, plus schools",
      covers: "Competition slot. 2026 travel funding was not a published full package.",
      eligibility: "African students. 2026 Mars-stage final was held 25 Sep 2026. Next call not posted.",
      deadline: "Forecast spring 2027 watch",
      link: "https://www.sansa.org.za/2026/09/africas-young-innovators-test-mars-rovers-at-sansa/",
      linkLabel: "SANSA 2026 final report",
      aerospace: "Hands-on rover design, mobility, and Mars-yard testing.",
      next: "Watch for the 2027 call. Do not pay an agent for a closed season."
    }
  ],
  excluded: [
    {
      id: "ieee-aess",
      name: "IEEE AESS Engineering Scholarship",
      status: "excluded",
      type: "Scholarship",
      destination: "-",
      level: "EE undergrad / systems or EE graduate",
      covers: "-",
      eligibility: "Electrical Engineering focus - not Mechanical.",
      deadline: "Do not apply",
      link: "https://ieee-aess.org/",
      linkLabel: "IEEE AESS",
      aerospace: "Excluded by field filter.",
      next: "Skip."
    },
    {
      id: "ieee-wie",
      name: "IEEE WIE International Scholarship",
      status: "excluded",
      type: "Cash scholarship",
      destination: "No host placement",
      level: "Engineering undergrad after 2 years",
      covers: "USD 2,500 and a certificate. Not travel.",
      eligibility: "Needs two consecutive years of IEEE WIE student membership and about 3.7/4.0. Women-in-engineering award.",
      deadline: "8 Nov 2026 (skip unless already a 2-year WIE member)",
      link: "https://wie.ieee.org/grants-scholarships/international-scholarship/",
      linkLabel: "IEEE WIE scholarship",
      aerospace: "Not a placement. Membership lock.",
      next: "Skip unless both membership conditions are already true."
    },
    {
      id: "nasa-ostem",
      name: "NASA OSTEM internships",
      status: "excluded",
      type: "Internship",
      destination: "United States",
      level: "US citizen students",
      covers: "Paid internships",
      eligibility: "US citizens only. Summer 2027 session is not open to this profile.",
      deadline: "N/A for this profile",
      link: "https://www.nasa.gov/learning-resources/internship-programs/",
      linkLabel: "NASA internships",
      aerospace: "Blocked by citizenship.",
      next: "Skip."
    },
    {
      id: "nasa-i2",
      name: "NASA International Internship (I2)",
      status: "excluded",
      type: "Internship",
      destination: "United States",
      level: "Partner-country citizens only",
      covers: "-",
      eligibility: "Paused; Nigeria is not a partner country.",
      deadline: "N/A",
      link: "https://www.nasa.gov/learning-resources/internship-programs/nasa-international-intern-opportunities-for-students/",
      linkLabel: "NASA I2 notice",
      aerospace: "Blocked by nationality / partner list.",
      next: "Skip."
    },
    {
      id: "nasa-orbit",
      name: "NASA ORBIT 2026-27 challenge",
      status: "excluded",
      type: "Student challenge",
      destination: "United States",
      level: "Students enrolled at a US college",
      covers: "Challenge participation",
      eligibility: "US college enrolment required.",
      deadline: "16 Nov 2026 (wrong enrolment)",
      link: "https://www.nasa.gov/",
      linkLabel: "NASA",
      aerospace: "Blocked by enrolment rule.",
      next: "Skip."
    },
    {
      id: "esa-ygt",
      name: "ESA Young Graduate Trainee",
      status: "excluded",
      type: "Graduate traineeship",
      destination: "ESA sites, Europe",
      level: "Recent master's graduates",
      covers: "Paid traineeship",
      eligibility: "ESA member or agreement-state nationals. Nigeria is not eligible.",
      deadline: "N/A",
      link: "https://www.esa.int/About_Us/Careers_at_ESA",
      linkLabel: "ESA careers",
      aerospace: "Blocked by nationality.",
      next: "Skip."
    },
    {
      id: "esa-cansat",
      name: "ESA Academy CanSat / member-state training",
      status: "excluded",
      type: "Training",
      destination: "Europe",
      level: "ESA member-state students",
      covers: "Sponsored training when selected",
      eligibility: "Citizen of an ESA Member State or agreement state. Nigeria is not eligible.",
      deadline: "N/A",
      link: "https://www.esa.int/Education/ESA_Academy/ESA_Training_Programme_Application_procedure",
      linkLabel: "ESA Academy eligibility",
      aerospace: "Blocked by nationality.",
      next: "Skip. Use AfSA joint calls instead."
    },
    {
      id: "esa-experiments",
      name: "ESA Academy Experiments Programme 2026-27",
      status: "excluded",
      type: "Student experiment",
      destination: "Parabolic flights / Orbital Robotics Lab, Europe",
      level: "Bachelor's, master's, or PhD teams from eligible states",
      covers: "Platform access and expert support. Not a Nigerian route.",
      eligibility: "Eligible states only. Call is open until 22 Nov 2026 23:59 CET. Nigeria is not an ESA member or agreement state.",
      deadline: "22 Nov 2026 (do not apply)",
      link: "https://www.esa.int/Education/ESA_Academy_Experiments_programme/Announcement_of_opportunity_for_the_ESA_Academy_Experiments_Programme_2026-2027",
      linkLabel: "ESA Experiments call",
      aerospace: "Direct microgravity and robotics. Blocked by nationality.",
      next: "Skip. REXUS/BEXUS also closed 8 Oct 2026 and is member-state only."
    },
    {
      id: "rise-germany",
      name: "DAAD RISE Germany",
      status: "excluded",
      type: "Summer research",
      destination: "Germany",
      level: "Undergraduates at US, Canada, UK, or Ireland institutions",
      covers: "Stipend and travel support",
      eligibility: "2027 window is 15 Oct-30 Nov 2026, but Nigerian universities are not eligible home institutions.",
      deadline: "30 Nov 2026 (ineligible)",
      link: "https://www.daad.de/rise/en/rise-germany/find-an-internship/application-portal/",
      linkLabel: "RISE Germany",
      aerospace: "Blocked by home-institution country.",
      next: "Skip."
    },
    {
      id: "rise-worldwide",
      name: "DAAD RISE Worldwide",
      status: "excluded",
      type: "Summer research",
      destination: "Various",
      level: "German students going abroad",
      covers: "-",
      eligibility: "For students enrolled in Germany, not incoming Nigerians.",
      deadline: "N/A",
      link: "https://www.daad.de/rise/en/",
      linkLabel: "DAAD RISE",
      aerospace: "Wrong direction of exchange.",
      next: "Skip."
    },
    {
      id: "mitacs",
      name: "Mitacs Globalink Research Internship",
      status: "excluded",
      type: "Research internship",
      destination: "Canada",
      level: "Undergraduates from listed countries",
      covers: "Funded 12-week internship",
      eligibility: "Nigeria is not on the 2027 country list. Call closed 16 Sep 2026.",
      deadline: "Closed / ineligible",
      link: "https://www.mitacs.ca/our-programs/globalink-research-internship-students/",
      linkLabel: "Mitacs Globalink",
      aerospace: "Blocked by nationality list.",
      next: "Skip."
    },
    {
      id: "epfl-erip",
      name: "EPFL Excellence Research Internship Program",
      status: "excluded",
      type: "Research internship",
      destination: "EPFL, Switzerland",
      level: "Partner-university students",
      covers: "Partner track only",
      eligibility: "Not the open E3 track. Nigerian universities are not ERIP partners.",
      deadline: "N/A",
      link: "https://eee.epfl.ch/",
      linkLabel: "Use E3 instead",
      aerospace: "Use the open E3 call.",
      next: "Apply to E3, not ERIP."
    },
    {
      id: "vki-stp",
      name: "VKI Short Training Programme",
      status: "excluded",
      type: "Short course",
      destination: "Belgium",
      level: "Typically completed degree plus fee",
      covers: "Not a funded undergraduate placement",
      eligibility: "Fee-based short course, not a paid undergrad internship.",
      deadline: "N/A",
      link: "https://www.vki.ac.be/",
      linkLabel: "VKI",
      aerospace: "Aerospace fluids exist, funding does not fit this profile.",
      next: "Skip."
    },
    {
      id: "zonta-ae",
      name: "Zonta Amelia Earhart Fellowship",
      status: "excluded",
      type: "Fellowship",
      destination: "Any PhD institution",
      level: "Women in doctoral aerospace programmes",
      covers: "Fellowship for doctoral research",
      eligibility: "Doctoral women only. Not an undergraduate award.",
      deadline: "Around 15 Nov 2026 (wrong level)",
      link: "https://www.zonta.org/Web/Programs/Education/Amelia_Earhart_Fellowship",
      linkLabel: "Amelia Earhart Fellowship",
      aerospace: "Direct aerospace, blocked by degree level.",
      next: "Skip until a PhD."
    },
    {
      id: "sg-nigeria",
      name: "Space Generation Nigeria 2026",
      status: "excluded",
      type: "Local conference ticket",
      destination: "Abuja, Nigeria",
      level: "Students and young professionals",
      covers: "Delegate pass only. Travel, accommodation, and visa are not paid.",
      eligibility: "Opened 6 Oct 2026. Must attend 23-27 Nov 2026. Ticket-only; no travel package.",
      deadline: "23 Oct 2026, 23:59 WAT",
      link: "https://spacegeneration.org/sgnigeria2026",
      linkLabel: "SG Nigeria page",
      aerospace: "Local networking only unless self-funded in Abuja.",
      next: "Skip unless already in Abuja and able to self-fund the stay."
    },
    {
      id: "domestic-generic",
      name: "Other domestic awards (no aerospace path)",
      status: "excluded",
      type: "Local scholarship",
      destination: "Nigeria",
      level: "Varies",
      covers: "Tuition or stipend local only",
      eligibility: "Julius Berger female 200L closed mid-Sep; Indomie for new admits; STEM to Space closed 2 Apr 2026; Borno Zulum aeronautics scheme is state-indigene only.",
      deadline: "Various / closed",
      link: "https://iaeste.ng/index.php/students/",
      linkLabel: "Prefer IAESTE for abroad",
      aerospace: "Use Carewave, Shell SIWES, GEF, or PTDF when eligible instead of random local lists.",
      next: "Prefer listed local items that match Mech and your level."
    },
    {
      id: "imeche-ug",
      name: "IMechE undergraduate scholarship",
      status: "excluded",
      type: "Scholarship",
      destination: "United Kingdom",
      level: "UK residents starting an accredited degree",
      covers: "Up to GBP 8,000 over the degree",
      eligibility: "UK residents only.",
      deadline: "Ineligible",
      link: "https://www.imeche.org/careers-education/scholarships-and-awards/undergraduate-and-apprentice-awards/scholarships",
      linkLabel: "IMechE scholarships",
      aerospace: "Blocked by residency.",
      next: "Skip."
    },
    {
      id: "arc-hs",
      name: "American Rocketry Challenge",
      status: "excluded",
      type: "High-school competition",
      destination: "United States",
      level: "Secondary-school teams",
      covers: "Contest entry; travel not funded for this profile",
      eligibility: "High-school challenge. Not an undergraduate call.",
      deadline: "Wrong level",
      link: "https://rocketcontest.org/",
      linkLabel: "ARC",
      aerospace: "Rocketry exists, blocked by school level.",
      next: "Skip."
    }
  ],
  nextSteps: [
    { when: "By 11 October", what: "One-page CV, transcript request, two referee names for EPFL E3." },
    { when: "12 October - 1 November", what: "Submit E3 in the first week the portal opens." },
    { when: "15-31 October", what: "AIAA DBF only if a real team can file a proposal. Otherwise skip." },
    { when: "This month", what: "Start KAUST VSRP file; email one mechanical/fluids faculty; check passport validity." },
    { when: "This month", what: "Email IAESTE Nigeria; apply Shell SIWES with SIWES letter; start Carewave if CGPA and need docs fit." },
    { when: "By 9 November", what: "Carewave Aspire portal submission if eligible." },
    { when: "Always", what: "Ignore paid agents. NASA, ESA direct calls, and DAAD RISE remain blocked for this profile." }
  ]
};
