window.BOARD = {
  updated: "2026-10-02",
  timezone: "Africa/Lagos",
  profile: "Nigerian Mechanical Engineering undergraduate, 300 level, aerospace / space focus",
  summary:
    "No NASA or ESA internship is open to this profile. Act first on EPFL E3 (portal opens 12 Oct, closes 1 Nov), keep a rolling KAUST VSRP file, register with IAESTE Nigeria, and only treat SIPGA as live after the official project list confirms an October cycle.",
  stats: {
    urgent: 1,
    open: 3,
    forecast: 4,
    excluded: 8
  },
  deadlines: [
    { date: "2026-10-09", label: "IAESTE register", hint: "Check mechanical offers", status: "open" },
    { date: "2026-10-12", label: "EPFL E3 opens", hint: "Portal day — apply early", status: "urgent" },
    { date: "2026-10-16", label: "KAUST VSRP file", hint: "Rolling; passport + mentor email", status: "open" },
    { date: "2026-10-20", label: "Commonwealth window", hint: "Masters only — not eligible yet", status: "forecast" },
    { date: "2026-10-31", label: "SIPGA cycle check", hint: "Verify official project list", status: "forecast" },
    { date: "2026-11-01", label: "EPFL E3 deadline", hint: "Summer 2027 research", status: "urgent" },
    { date: "2027-01-31", label: "CERN Summer forecast", hint: "Need 6 semesters by summer", status: "forecast" }
  ],
  opportunities: [
    {
      id: "epfl-e3",
      name: "EPFL Excellence in Engineering (E3)",
      status: "urgent",
      type: "Summer research",
      destination: "EPFL, Switzerland",
      level: "BSc / MSc (2+ years completed)",
      covers: "Paid research stay (~CHF 1,800/mo in recent cycles). Confirm 2027 stipend on portal. 2–3 months from May.",
      eligibility: "International students. Mechanical engineering is named on the official page. Strong academic record expected.",
      deadline: "Portal opens 12 Oct 2026 · closes 1 Nov 2026",
      link: "https://eee.epfl.ch/",
      linkLabel: "Open EPFL E3 site",
      aerospace: "Mechanical, microengineering, and materials research next to aerospace structures, UAVs, and mechanisms.",
      next: "CV, English transcript, statement tied to a lab, two referees ready before 12 October."
    },
    {
      id: "kaust-vsrp",
      name: "KAUST Visiting Student Research Program (VSRP)",
      status: "open",
      type: "Research internship",
      destination: "KAUST, Saudi Arabia",
      level: "3rd-year bachelor’s or master’s",
      covers: "USD 1,000/month, private room, visa & airfare, health insurance, 3–6 months.",
      eligibility: "All nationalities. GPA ~3.5/4.0. English. Transcript, recommendation, valid passport.",
      deadline: "Rolling (arrival ≥ 6 weeks after submission)",
      link: "https://kaust-vsrp.azurewebsites.net/about-vsrp",
      linkLabel: "Open KAUST VSRP",
      aerospace: "Fluids, combustion, composites, thermal systems — mechanical core of propulsion and airframes.",
      next: "Pick a Mechanical / PSE faculty project, email a short research note, then submit."
    },
    {
      id: "iaeste",
      name: "IAESTE Nigeria paid internships",
      status: "open",
      type: "Paid internship / exchange",
      destination: "80+ countries (offer-dependent)",
      level: "Enrolled undergrad, age 19–30, usually after 4 semesters",
      covers: "Local living-cost salary; visa & accommodation support. You pay national participation fee + passport.",
      eligibility: "Nigerian university students via IAESTE Nigeria. Mechanical engineering is a core field.",
      deadline: "Offer-driven (peak after January exchange conference)",
      link: "https://iaeste.ng/index.php/students/",
      linkLabel: "IAESTE Nigeria students",
      aerospace: "Filter offers for aerospace, automotive, energy, manufacturing, or design offices.",
      next: "Email nigeria@iaeste.org — English CV, subject list, passport biodata. Pay only the national committee."
    },
    {
      id: "sipga",
      name: "A*STAR SIPGA (Singapore)",
      status: "forecast",
      type: "Research attachment",
      destination: "A*STAR institutes, Singapore",
      level: "3rd / 4th year undergrad or master’s",
      covers: "About SGD 2,000/month for 2–6 months. Travel not always fully covered.",
      eligibility: "International STEM; on track for ≥ Second Class Upper equivalent.",
      deadline: "Historical cycles ~31 Mar / 31 Jul / 31 Oct — verify list before treating as open",
      link: "https://www.a-star.edu.sg/Scholarships/for-undergraduate-studies/singapore-international-pre-graduate-award-sipga",
      linkLabel: "Open SIPGA page",
      aerospace: "Materials, robotics, manufacturing, computational engineering bridge — not a launch internship.",
      next: "Open the project list. Apply only if a mechanical-relevant project is posted."
    },
    {
      id: "cern-summer",
      name: "CERN Summer Student Programme",
      status: "forecast",
      type: "Summer technical studentship",
      destination: "CERN, Geneva, Switzerland",
      level: "Bachelor’s or master’s; ≥ 6 semesters by summer start",
      covers: "94 CHF/day, insurance, housing help, possible travel support; 8–13 weeks.",
      eligibility: "All nationalities (US/Canada/Japan use national routes). Engineering eligible. Still enrolled.",
      deadline: "Forecast close end of January 2027 — confirm on careers.cern",
      link: "https://careers.cern/programmes/summer-studentship/",
      linkLabel: "CERN Summer Studentship",
      aerospace: "Vacuum, cryogenics, detectors, mechanical systems at a major lab.",
      next: "Target summer 2027 only if six semesters will be complete; otherwise plan 2028."
    },
    {
      id: "sgac",
      name: "SGAC / Space Generation Congress scholarships",
      status: "forecast",
      type: "Conference scholarship",
      destination: "Varies (SGC + IAC host city)",
      level: "Students & young professionals 18–35",
      covers: "Often partial travel / registration for SGC and related events.",
      eligibility: "Open worldwide. Competitive; essay and CV driven.",
      deadline: "Typical spring call before autumn congress",
      link: "https://spacegeneration.org/scholarships",
      linkLabel: "SGAC scholarships",
      aerospace: "Direct space-sector networking and policy/technical sessions.",
      next: "Watch the scholarships page from March; prepare a one-page space motivation statement."
    },
    {
      id: "unisec",
      name: "UNISEC Mission Idea Contest / CLTP",
      status: "forecast",
      type: "Competition / training",
      destination: "Japan / rotating hosts",
      level: "University student teams and individuals",
      covers: "Sometimes partial travel for selected participants.",
      eligibility: "International student teams; CLTP15 (Aug 2026) has passed.",
      deadline: "Next CLTP / MIC window forecast H2 2027",
      link: "https://www.unisec-global.org/calendar.html",
      linkLabel: "UNISEC calendar",
      aerospace: "CubeSat / CanSat hands-on pathway into small-satellite engineering.",
      next: "Join or form a campus satellite team early; monitor the calendar."
    },
    {
      id: "commonwealth",
      name: "Commonwealth Master’s Scholarship (UK)",
      status: "forecast",
      type: "Postgraduate scholarship",
      destination: "United Kingdom",
      level: "Requires completed bachelor’s degree",
      covers: "Fully funded one-year master’s (typical CSC package).",
      eligibility: "Not for current undergrads without a degree. Engineering & technology is a theme.",
      deadline: "Nigeria window reported 20 Oct 2026 — do not apply this cycle",
      link: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
      linkLabel: "CSC Master’s scholarships",
      aerospace: "Post-graduation route into UK aerospace / mechanical master’s programmes.",
      next: "File under 2028/29 targets after graduation."
    }
  ],
  excluded: [
    {
      id: "ieee-aess",
      name: "IEEE AESS Engineering Scholarship",
      status: "excluded",
      type: "Scholarship",
      destination: "—",
      level: "EE undergrad / systems or EE graduate",
      covers: "—",
      eligibility: "Electrical Engineering focus — not Mechanical.",
      deadline: "Do not apply",
      link: "https://ieee-aess.org/",
      linkLabel: "IEEE AESS",
      aerospace: "Excluded by field filter.",
      next: "Skip."
    },
    {
      id: "nasa-ostem",
      name: "NASA OSTEM internships",
      status: "excluded",
      type: "Internship",
      destination: "United States",
      level: "US citizen students",
      covers: "Paid internships",
      eligibility: "US citizens only.",
      deadline: "N/A for this profile",
      link: "https://nasa.gov/learning-resources/internship-programs",
      linkLabel: "NASA internships",
      aerospace: "Blocked by citizenship.",
      next: "Skip."
    },
    {
      id: "nasa-i2",
      name: "NASA International Internship (I²)",
      status: "excluded",
      type: "Internship",
      destination: "United States",
      level: "Partner-country citizens only",
      covers: "—",
      eligibility: "Paused; Nigeria is not a partner country.",
      deadline: "N/A",
      link: "https://www.nasa.gov/learning-resources/internship-programs/nasa-international-intern-opportunities-for-students/",
      linkLabel: "NASA I² notice",
      aerospace: "Blocked by nationality / partner list.",
      next: "Skip."
    },
    {
      id: "esa-ygt",
      name: "ESA Graduate / Young Graduate Trainee",
      status: "excluded",
      type: "Graduate traineeship",
      destination: "Europe",
      level: "Master’s + ESA member-state national",
      covers: "Paid traineeship",
      eligibility: "ESA member / associate / cooperating states only.",
      deadline: "N/A",
      link: "https://www.esa.int/About_Us/Careers_at_ESA",
      linkLabel: "ESA careers",
      aerospace: "Blocked by nationality and degree level.",
      next: "Skip."
    },
    {
      id: "rise-germany",
      name: "DAAD RISE Germany",
      status: "excluded",
      type: "Summer research",
      destination: "Germany",
      level: "Undergrads at US/Canada/UK/Ireland universities",
      covers: "Scholarship + travel stipend",
      eligibility: "University of enrolment blocks this profile.",
      deadline: "15 Oct–30 Nov 2026 (ineligible)",
      link: "https://www.daad.de/rise/",
      linkLabel: "DAAD RISE",
      aerospace: "Blocked by home-university country rule.",
      next: "Skip."
    },
    {
      id: "mitacs",
      name: "Mitacs Globalink 2027",
      status: "excluded",
      type: "Research internship",
      destination: "Canada",
      level: "Listed partner countries only",
      covers: "Funded summer research",
      eligibility: "Nigeria not on eligible-country list; 16 Sep 2026 deadline passed.",
      deadline: "Closed for 2027 cycle",
      link: "https://www.mitacs.ca/",
      linkLabel: "Mitacs",
      aerospace: "Blocked by country list.",
      next: "Skip."
    },
    {
      id: "epfl-erip",
      name: "EPFL Excellence Research Internship (ERIP)",
      status: "excluded",
      type: "Research internship",
      destination: "EPFL, Switzerland",
      level: "Partner universities only",
      covers: "Funded internship",
      eligibility: "North America & Singapore partners only — use E3 instead.",
      deadline: "N/A for this profile",
      link: "https://www.epfl.ch/education/international/en/coming-to-epfl/research-internships/",
      linkLabel: "EPFL internships",
      aerospace: "Wrong EPFL route; E3 is the open one.",
      next: "Use EPFL E3."
    },
    {
      id: "domestic",
      name: "Domestic Nigerian awards (no travel)",
      status: "excluded",
      type: "Local scholarship",
      destination: "Nigeria",
      level: "Varies",
      covers: "Tuition / stipend local only",
      eligibility: "No abroad exposure component.",
      deadline: "Various",
      link: "#",
      linkLabel: "Not listed",
      aerospace: "Excluded by travel filter (except passport/visa bridge costs).",
      next: "Skip unless pure bridge funding for passport/visa."
    }
  ],
  nextSteps: [
    { when: "By 11 October", what: "One-page CV, transcript request, two referee names for EPFL E3." },
    { when: "12 October – 1 November", what: "Submit E3 as soon as the portal opens — do not wait for the last day." },
    { when: "This month", what: "Start KAUST VSRP file; email one mechanical/fluids faculty; check passport validity." },
    { when: "This month", what: "Register with IAESTE Nigeria and ask which mechanical offers are live." },
    { when: "Before 31 October", what: "Open SIPGA project list; apply only if a mechanical project is actually posted." },
    { when: "Always", what: "Ignore paid agents offering NASA / ESA / DAAD submissions for this profile." }
  ]
};
